### ISSUE TITLE
etcdbackuprecovery panic

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#1034]
@charlesakalugwu probably related to the routing changes
```
$ make e2e-etcdbackuprecovery
FOCUS="\[EtcdRecovery\]\[Fake\]" TIMEOUT=70m ./hack/e2e.sh
bindata.go
bindata.go
=== RUN   TestE2E
e2e tests starting, git commit COMMIT
Running Suite: e2e tests
========================
Random Seed: 1547218774
Will run 1 of 32 specs

SSSSSSSSSSSSSSSSSSSSS
------------------------------
Etcd Recovery E2E tests [EtcdRecovery][Fake][LongRunning] 
  should be possible to recover etcd from a backup
  /home/kargakis/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/etcdrecovery.go:62
INFO[2019-01-11T15:59:34+01:00] starting the fake resource provider          
INFO[2019-01-11T15:59:34+01:00] starting server on localhost:8080            
configuring the fake resource provider
Using namespace e2e-test-b5fb7
STEP: Create a test configmap with value=first
STEP: Run an etcd backup using quay.io/openshift-on-azure/etcdbackup:latest
STEP: Overwrite the test configmap with value=second
STEP: Restore from the backup
DEBU[2019-01-11T15:59:45+01:00] 127.0.0.1:41850 PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups//providers/Microsoft.ContainerService/openShiftManagedClusters//restore?api-version=admin 
INFO[2019-01-11T15:59:47+01:00] generating arm templates                     
Panic: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
runtime/debug.Stack(0x48, 0x0, 0x0)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/golang/src/runtime/debug/stack.go:16 +0x22
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc0003e8200, 0x15614c0, 0xc0000bb3b0)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware/recoverer.go:28 +0x1b6
panic(0x126f400, 0x20e8fe0)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
github.com/openshift/openshift-azure/pkg/arm.Vmss(0xc00008cb80, 0xc000476000, 0xc00039c7e0, 0xc0003ab1f1, 0xe, 0xc0003c8290, 0xa, 0x0, 0x200, 0x12c7fe0)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/arm/resources.go:442 +0x41
github.com/openshift/openshift-azure/pkg/arm.(*simpleGenerator).Generate(0xc00008cb80, 0x156dd80, 0xc0003b46c0, 0xc000476000, 0xc0003ab1f1, 0xe, 0x1, 0xc0003c8290, 0xa, 0x7fadf74b66c0, ...)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/arm/arm.go:63 +0xb78
github.com/openshift/openshift-azure/pkg/plugin.(*plugin).RecoverEtcdCluster(0xc000184a20, 0x156dd80, 0xc0003b46c0, 0xc000476000, 0xc0001f6dc0, 0xc0003ab1f1, 0xe, 0xc0003b46c0)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/plugin/plugin.go:75 +0x1bb
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handleRestore(0xc0003e8000, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/fakerp/restore.go:91 +0x954
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handleRestore-fm(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/fakerp/server.go:81 +0x48
net/http.HandlerFunc.ServeHTTP(0xc000183600, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000fa180, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/mux.go:424 +0x239
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi.(*Mux).routeHTTP-fm(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/mux.go:368 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0001834b0, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).validator.func1(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:28 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc0000fcee0, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:10 +0x15a
net/http.HandlerFunc.ServeHTTP(0xc0000fcf00, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware.Recoverer.func1(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware/recoverer.go:35 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc0000fcf20, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware.RedirectSlashes.func1(0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware/strip.go:45 +0xb5
net/http.HandlerFunc.ServeHTTP(0xc0000fcf40, 0x15614c0, 0xc0000bb3b0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware.Compress.func1.1(0x156ce80, 0xc0003cc0e0, 0xc0003e8200)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware/compress.go:132 +0x183
net/http.HandlerFunc.ServeHTTP(0xc00033bfb0, 0x156ce80, 0xc0003cc0e0, 0xc0003e8200)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000fa180, 0x156ce80, 0xc0003cc0e0, 0xc0003e8100)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/mux.go:81 +0x293
net/http.serverHandler.ServeHTTP(0xc0003b9380, 0x156ce80, 0xc0003cc0e0, 0xc0003e8100)
	/usr/lib/golang/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001cc0a0, 0x156dcc0, 0xc00008d240)
	/usr/lib/golang/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2851 +0x2f5
^C
Ran 1 of 22 Specs in 24.289 seconds
FAIL! -- 1 Passed | 0 Failed | 0 Pending | 21 Skipped
signal: interrupt
FAIL	github.com/openshift/openshift-azure/test/e2e	24.314s
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
make: *** [e2e-etcdbackuprecovery] Error 1

```
/kind bug

**Comment by charlesakalugwu** [comment]
I was able to reproduce this and it was caused by running the etcdbackupandrestore test right after a failed key rotation test. The [test](https://github.com/openshift/openshift-azure/blob/3f74ce29ff1b48eb8fe1625f04a4eb586c4b1583/test/e2e/specs/fakerp/keyrotation.go#L46) calls `saveConfig` right after the certs are invalidated. So for a while containerservice.yaml has no values for some fields such as the SSHKey which is where the test panics. 

If you perform the test on a fresh cluster everything works fine

```
charles@titan:~/Documents/go/src/github.com/openshift/openshift-azure$ make create && make e2e-etcdbackuprecovery 
timeout 1h ./hack/create.sh charles-dev
+ [[ 1 -ne 1 ]]
+ export RESOURCEGROUP=charles-dev
+ RESOURCEGROUP=charles-dev
+ rm -rf _data
+ mkdir -p _data/_out
+ set -x
+ [[ -n '' ]]
+ go generate ./...
bindata.go
bindata.go
+ [[ -n '' ]]
+ trap 'return_id=$?; set +ex; kill $(lsof -t -i :8080); wait $(lsof -t -i :8080); exit $return_id' EXIT
+ go run cmd/fakerp/main.go
+ go run cmd/createorupdate/createorupdate.go
INFO[2019-01-11T19:42:44+01:00] creating resource group charles-dev          
INFO[2019-01-11T19:42:45+01:00] starting the fake resource provider          
INFO[2019-01-11T19:42:45+01:00] starting server on localhost:8080            
INFO[2019-01-11T19:42:46+01:00] updating the aad application                 
INFO[2019-01-11T19:42:48+01:00] creating/updating cluster                    
DEBU[2019-01-11T19:42:48+01:00] 127.0.0.1:43374 PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev?api-version=2018-09-30-preview 
INFO[2019-01-11T19:42:48+01:00] read request and convert to internal         
INFO[2019-01-11T19:42:48+01:00] validating external plugin api data models   
INFO[2019-01-11T19:42:55+01:00] enrich                                       
INFO[2019-01-11T19:42:55+01:00] validating internal data models              
INFO[2019-01-11T19:42:55+01:00] generating configs                           
INFO[2019-01-11T19:43:00+01:00] persist config                               
INFO[2019-01-11T19:43:00+01:00] write helpers                                
INFO[2019-01-11T19:43:00+01:00] generating arm templates                     
INFO[2019-01-11T19:43:00+01:00] starting deploy                              
INFO[2019-01-11T19:43:00+01:00] applying arm template deployment             
INFO[2019-01-11T19:43:06+01:00] waiting for arm template deployment to complete 
INFO[2019-01-11T19:48:20+01:00] waiting for master-000000 to be ready        
INFO[2019-01-11T19:49:37+01:00] waiting for master-000001 to be ready        
INFO[2019-01-11T19:49:37+01:00] waiting for master-000002 to be ready        
INFO[2019-01-11T19:49:39+01:00] waiting for infra-1547232180-000000 to be ready 
INFO[2019-01-11T19:50:41+01:00] waiting for infra-1547232180-000001 to be ready 
INFO[2019-01-11T19:50:57+01:00] waiting for compute-1547232180-000000 to be ready 
INFO[2019-01-11T19:50:57+01:00] waiting for infra services to be ready       
INFO[2019-01-11T19:50:57+01:00] checking daemonset default/docker-registry   
INFO[2019-01-11T19:53:07+01:00] checking daemonset default/router            
INFO[2019-01-11T19:53:07+01:00] checking daemonset openshift-node/sync       
INFO[2019-01-11T19:53:07+01:00] checking daemonset openshift-sdn/ovs         
INFO[2019-01-11T19:53:07+01:00] checking daemonset openshift-sdn/sdn         
INFO[2019-01-11T19:53:07+01:00] checking daemonset kube-service-catalog/apiserver 
INFO[2019-01-11T19:53:07+01:00] checking daemonset kube-service-catalog/controller-manager 
INFO[2019-01-11T19:53:07+01:00] checking daemonset openshift-template-service-broker/apiserver 
INFO[2019-01-11T19:53:07+01:00] checking daemonset openshift-azure-logging/mdsd 
INFO[2019-01-11T19:53:30+01:00] checking statefulset openshift-infra/bootstrap-autoapprover 
INFO[2019-01-11T19:53:30+01:00] checking deployment default/registry-console 
INFO[2019-01-11T19:53:30+01:00] checking deployment openshift-infra/customer-admin-controller 
INFO[2019-01-11T19:53:30+01:00] checking deployment openshift-ansible-service-broker/asb 
INFO[2019-01-11T19:53:30+01:00] checking deployment openshift-web-console/webconsole 
INFO[2019-01-11T19:53:30+01:00] checking deployment openshift-console/console 
INFO[2019-01-11T19:53:30+01:00] starting health check                        
INFO[2019-01-11T19:53:30+01:00] checking developer console health            
INFO[2019-01-11T19:53:31+01:00] checking admin console health                
DEBU[2019-01-11T19:53:31+01:00] 127.0.0.1:43374 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev?api-version=2018-09-30-preview 
INFO[2019-01-11T19:53:31+01:00] created/updated cluster                      

Cluster available at https://charles-dev.westeurope.cloudapp.azure.com/
+ return_id=0
+ set +ex
signal: terminated
FOCUS="\[EtcdRecovery\]\[Fake\]" TIMEOUT=70m ./hack/e2e.sh
bindata.go
bindata.go
=== RUN   TestE2E
e2e tests starting, git commit COMMIT
Running Suite: e2e tests
========================
Random Seed: 1547232821
Will run 1 of 32 specs

SSSSSSSSSSSSS
------------------------------
Etcd Recovery E2E tests [EtcdRecovery][Fake][LongRunning] 
  should be possible to recover etcd from a backup
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/etcdrecovery.go:62
INFO[2019-01-11T19:53:41+01:00] starting the fake resource provider          
INFO[2019-01-11T19:53:41+01:00] starting server on localhost:8080            
configuring the fake resource provider
Using namespace e2e-test-ugmr2
STEP: Create a test configmap with value=first
STEP: Run an etcd backup using quay.io/openshift-on-azure/etcdbackup:latest
STEP: Overwrite the test configmap with value=second
STEP: Restore from the backup
DEBU[2019-01-11T19:54:08+01:00] 127.0.0.1:43560 PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev/restore?api-version=admin 
INFO[2019-01-11T19:54:09+01:00] generating arm templates                     
INFO[2019-01-11T19:54:09+01:00] restoring the cluster                        
INFO[2019-01-11T19:55:10+01:00] applying arm template deployment             
INFO[2019-01-11T19:55:16+01:00] waiting for arm template deployment to complete 
INFO[2019-01-11T20:02:13+01:00] waiting for master-000000 to be ready        
INFO[2019-01-11T20:02:13+01:00] waiting for master-000001 to be ready        
INFO[2019-01-11T20:03:05+01:00] waiting for master-000002 to be ready        
INFO[2019-01-11T20:03:06+01:00] running CreateOrUpdate                       
INFO[2019-01-11T20:03:06+01:00] generating arm templates                     
INFO[2019-01-11T20:03:06+01:00] starting update                              
INFO[2019-01-11T20:03:06+01:00] applying arm template deployment             
INFO[2019-01-11T20:03:12+01:00] waiting for arm template deployment to complete 
INFO[2019-01-11T20:04:24+01:00] draining master-000000                       
INFO[2019-01-11T20:04:24+01:00] deallocating master-000000                   
INFO[2019-01-11T20:05:55+01:00] updating master-000000                       
INFO[2019-01-11T20:08:07+01:00] reimaging master-000000                      
INFO[2019-01-11T20:09:18+01:00] starting master-000000                       
INFO[2019-01-11T20:11:09+01:00] waiting for master-000000 to be ready        
INFO[2019-01-11T20:14:23+01:00] draining master-000001                       
INFO[2019-01-11T20:14:23+01:00] deallocating master-000001                   
INFO[2019-01-11T20:16:05+01:00] updating master-000001                       
INFO[2019-01-11T20:17:26+01:00] reimaging master-000001                      
INFO[2019-01-11T20:18:27+01:00] starting master-000001                       
INFO[2019-01-11T20:20:08+01:00] waiting for master-000001 to be ready        
INFO[2019-01-11T20:22:34+01:00] draining master-000002                       
INFO[2019-01-11T20:22:34+01:00] deallocating master-000002                   
INFO[2019-01-11T20:24:46+01:00] updating master-000002                       
INFO[2019-01-11T20:25:17+01:00] reimaging master-000002                      
INFO[2019-01-11T20:26:27+01:00] starting master-000002                       
INFO[2019-01-11T20:27:59+01:00] waiting for master-000002 to be ready        
INFO[2019-01-11T20:31:08+01:00] updating worker agent pool infra             
INFO[2019-01-11T20:31:08+01:00] found target scaleset ss-infra-1547232180    
INFO[2019-01-11T20:31:08+01:00] updating worker agent pool compute           
INFO[2019-01-11T20:31:09+01:00] found target scaleset ss-compute-1547232180  
INFO[2019-01-11T20:31:09+01:00] waiting for infra services to be ready       
INFO[2019-01-11T20:31:09+01:00] checking daemonset default/docker-registry   
INFO[2019-01-11T20:31:09+01:00] checking daemonset default/router            
INFO[2019-01-11T20:31:09+01:00] checking daemonset openshift-node/sync       
INFO[2019-01-11T20:31:09+01:00] checking daemonset openshift-sdn/ovs         
INFO[2019-01-11T20:31:09+01:00] checking daemonset openshift-sdn/sdn         
INFO[2019-01-11T20:31:09+01:00] checking daemonset kube-service-catalog/apiserver 
INFO[2019-01-11T20:31:50+01:00] checking daemonset kube-service-catalog/controller-manager 
INFO[2019-01-11T20:31:50+01:00] checking daemonset openshift-template-service-broker/apiserver 
INFO[2019-01-11T20:31:50+01:00] checking daemonset openshift-azure-logging/mdsd 
INFO[2019-01-11T20:32:09+01:00] checking statefulset openshift-infra/bootstrap-autoapprover 
INFO[2019-01-11T20:32:09+01:00] checking deployment default/registry-console 
INFO[2019-01-11T20:32:09+01:00] checking deployment openshift-infra/customer-admin-controller 
INFO[2019-01-11T20:32:09+01:00] checking deployment openshift-ansible-service-broker/asb 
INFO[2019-01-11T20:32:09+01:00] checking deployment openshift-web-console/webconsole 
INFO[2019-01-11T20:32:09+01:00] checking deployment openshift-console/console 
INFO[2019-01-11T20:32:09+01:00] starting health check                        
INFO[2019-01-11T20:32:09+01:00] checking developer console health            
INFO[2019-01-11T20:32:10+01:00] checking admin console health                
INFO[2019-01-11T20:32:10+01:00] recovered cluster                            
STEP: Confirm the state of the backup

• [SLOW TEST:2309.517 seconds]
Etcd Recovery E2E tests [EtcdRecovery][Fake][LongRunning]
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/etcdrecovery.go:25
  should be possible to recover etcd from a backup
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/etcdrecovery.go:62
------------------------------
SSSSSSSSSSSSSSSSSS
Ran 1 of 32 Specs in 2309.518 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 31 Skipped
--- PASS: TestE2E (2309.52s)
PASS
ok  	github.com/openshift/openshift-azure/test/e2e	2309.538s
signal: terminated
```

**Comment by charlesakalugwu** [comment]
As mentioned in the previous comment, this is not actually an issue. 

/close
