### ISSUE TITLE
Node exporter pod crashing due to insecure kube-rbac-proxy cipher suites

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1177]
The `node-exporter` daemonset pods are crashing due to specification of insecure cipher suites for their constituent `kube-rbac-proxy` containers.

*list monitoring pods*
```
[charles@akalugwu openshift-azure]$ kubectl get pods --namespace=openshift-monitoring
NAME                                          READY     STATUS             RESTARTS   AGE
alertmanager-main-0                           3/3       Running            0          1h
alertmanager-main-1                           3/3       Running            0          1h
alertmanager-main-2                           3/3       Running            0          1h
cluster-monitoring-operator-c4c9c784d-9lnc5   1/1       Running            0          1h
grafana-8497b48bd5-ls27x                      2/2       Running            0          1h
node-exporter-42w5q                           1/2       CrashLoopBackOff   24         1h
node-exporter-bxq2x                           1/2       CrashLoopBackOff   24         1h
node-exporter-ks8c8                           1/2       CrashLoopBackOff   24         1h
node-exporter-rdv7n                           1/2       CrashLoopBackOff   24         1h
node-exporter-s7tf2                           1/2       CrashLoopBackOff   24         1h
node-exporter-vhw88                           1/2       CrashLoopBackOff   24         1h
prometheus-k8s-0                              4/4       Running            1          1h
prometheus-k8s-1                              4/4       Running            1          1h
prometheus-operator-5677fb6f87-27gfm          1/1       Running            0          1h
```
*sample kube-rbac-proxy logs*
```
[charles@akalugwu openshift-azure]$ kubectl logs --namespace=openshift-monitoring node-exporter-42w5q -c kube-rbac-proxy
F0220 20:01:54.237883   57006 main.go:240] failed to configure http2 server: http2: TLSConfig.CipherSuites index 11 contains an HTTP/2-approved cipher suite (0xc02f), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection.
goroutine 1 [running]:
github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog.stacks(0xc4201fe400, 0xc42030e000, 0x163, 0x1b7)
	/go/src/github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog.(*loggingT).output(0x1a80580, 0xc400000003, 0xc4200de630, 0x19e36de, 0x7, 0xf0, 0x0)
	/go/src/github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog/glog.go:720 +0x32d
github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog.(*loggingT).printf(0x1a80580, 0xc400000003, 0x1210047, 0x24, 0xc42031fda0, 0x1, 0x1)
	/go/src/github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog.Fatalf(0x1210047, 0x24, 0xc42031fda0, 0x1, 0x1)
	/go/src/github.com/brancz/kube-rbac-proxy/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.main()
	/go/src/github.com/brancz/kube-rbac-proxy/main.go:240 +0x18fc
```

The faulty cipher suites which are configured with kube-rbac-proxy are:

```
[charles@akalugwu openshift-azure]$ kubectl describe pod --namespace=openshift-monitoring node-exporter-bxq2x
Name:               node-exporter-bxq2x
Namespace:          openshift-monitoring
Priority:           0
PriorityClassName:  <none>
Node:               compute-1550687736-000000/10.0.0.9
Start Time:         Wed, 20 Feb 2019 19:53:04 +0100
Labels:             app=node-exporter
                    controller-revision-hash=3598191539
                    pod-template-generation=1
Annotations:        openshift.io/scc=node-exporter
Status:             Running
IP:                 10.0.0.9
Controlled By:      DaemonSet/node-exporter
Containers:
  node-exporter:
    Container ID:  docker://cdf9094d91c13113d045bcf0545fa94a653c80df0eefdf0cc8d896b242bbe013
    Image:         registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11
    Image ID:      docker-pullable://registry.access.redhat.com/openshift3/prometheus-node-exporter@sha256:4fb35141df3be69ef1253963ca49b62a47650680583cf74a64330d26280d0ec9
    ...
  kube-rbac-proxy:
    Container ID:  docker://9072d03087289b4ec89a41d24d020b661ff4535f18290f525972aed6f3d0a447
    Image:         registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11
    Image ID:      docker-pullable://registry.access.redhat.com/openshift3/ose-kube-rbac-proxy@sha256:856e6c301b765d59c3e0fc3c2b22be577b99b1e553c6f929de0615b17af2bee1
    Port:          9100/TCP
    Host Port:     9100/TCP
    Args:
      --secure-listen-address=:9100
      --upstream=http://127.0.0.1:9101/
      ...
      --tls-cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    State:          Waiting
      Reason:       CrashLoopBackOff
.... 
```

Note: This issue was reported on [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1673178) and it is confirmed that this issue has been resolved with `OpenShift release 3.11.82-4`. This issue has also been referenced in the latest [bugfix advisory](https://access.redhat.com/errata/RHBA-2019:0326).

Since we are on release `3.11.69` we'll see this issue come up both during local and CI e2e test runs until we update to at least `3.11.82`.

*summary*
caused by https://github.com/openshift/cluster-monitoring-operator/pull/210
fixed in 3.11.82 by https://github.com/openshift/cluster-monitoring-operator/pull/241

/kind test-flake
/cc @openshift/sig-azure

**Comment by jim-minter** [comment]
@charlesakalugwu sample logging related to this issue is as follows:
```
time="2019-02-21T02:56:25Z" level=debug msg="validating that all monitoring components are healthy" func="github.com/openshift/openshift-azure/test/e2e/standard.(*SanityChecker).ValidateCluster" file="/go/src/github.com/openshift/openshift-azure/test/e2e/standard/sanitychecker.go:102"
time="2019-02-21T03:20:11Z" level=error msg="timed out waiting for the condition" func="github.com/openshift/openshift-azure/test/e2e/standard.(*SanityChecker).ValidateCluster" file="/go/src/github.com/openshift/openshift-azure/test/e2e/standard/sanitychecker.go:105"
```

please urgently add additional logging to checkMonitoringStackHealth so that it's clear which item is actually failing before this issue is closed.

**Comment by jim-minter** [comment]
@openshift/sig-azure we will need to get new images @ 3.11.82 to MSFT, our current push to them should not go to prod

**Comment by jim-minter** [comment]
I believe we can close this?
