### ISSUE TITLE
azure group controller crashes when mail is nil

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1498]
```
[mjudeiki@redhat openshift-azure]$ oc logs -f customer-admin-controller-776684f766-8gs4w
time="2019-04-12T12:35:42Z" level=info msg="azure-controller pod starting, git commit v4.0-154-gbf3371a-clean"
time="2019-04-12T12:35:42Z" level=info msg="starting manager"
time="2019-04-12T12:35:43Z" level=debug msg="NSC: reconciling namespace e2e-test-qmtf8"
time="2019-04-12T12:35:43Z" level=debug msg="NSC: creating rolebinding e2e-test-qmtf8/osa-customer-admin"
time="2019-04-12T12:35:43Z" level=debug msg="RBC: reconciling rolebinding e2e-test-qmtf8/osa-customer-admin"
time="2019-04-12T12:35:43Z" level=debug msg="RBC: reconciling rolebinding e2e-test-qmtf8/osa-customer-admin-project"
time="2019-04-12T12:35:43Z" level=debug msg="NSC: creating rolebinding e2e-test-qmtf8/osa-customer-admin-project"
time="2019-04-12T12:36:42Z" level=debug msg="AAD Group Reconciler (poll).."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x105a8e9]
goroutine 76 [running]:
github.com/openshift/openshift-azure/pkg/controllers/customeradmin.fromMSGraphGroup(0xc0000adc80, 0x0, 0x130fe98, 0x13, 0xc000254c60, 0x2, 0x2, 0x0, 0x0)                                                                                                                                
        /go/src/github.com/openshift/openshift-azure/pkg/controllers/customeradmin/group_mapping.go:34 +0x129
github.com/openshift/openshift-azure/pkg/controllers/customeradmin.updateKubeGroup(0xc0000adc80, 0x14847c0, 0xc0003c0440, 0x130fe98, 0x13, 0xc000254c60, 0x2, 0x2, 0x0, 0x1)                                                                                                             
        /go/src/github.com/openshift/openshift-azure/pkg/controllers/customeradmin/group_reconcile.go:23 +0x126
github.com/openshift/openshift-azure/pkg/controllers/customeradmin.reconcileGroups(0xc0000adc80, 0x14644a0, 0xc00033ea00, 0x14847c0, 0xc0003c0440, 0xc0004367b0, 0x42e4fb, 0x138adc8)                                                                                                    
        /go/src/github.com/openshift/openshift-azure/pkg/controllers/customeradmin/group_reconcile.go:53 +0xfa
github.com/openshift/openshift-azure/pkg/controllers/customeradmin.(*reconcileGroup).pollEvent(0xc000427080, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/openshift-azure/pkg/controllers/customeradmin/group_controller.go:100 +0xad
github.com/openshift/openshift-azure/pkg/controllers/customeradmin.(*reconcileGroup).pollEvent-fm(0x0, 0x0, 0x0, 0x0, 0xc00037f288)
        /go/src/github.com/openshift/openshift-azure/pkg/controllers/customeradmin/group_controller.go:75 +0x52
github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Generic(0x0, 0x0, 0x0, 0xc0003c0580, 0x0, 0x0, 0x0, 0x0, 0x101)                                                                                                                           
        /go/src/github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:86 +0x53
github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Channel).Start.func2(0xc0004444e0, 0xc0003c0590, 0x1, 0x1, 0x14809c0, 0x1fc0c18, 0x148f260, 0xc00042cf20)                                                                                        
        /go/src/github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:168 +0x18e
created by github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Channel).Start
        /go/src/github.com/openshift/openshift-azure/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:164 +0x120
```

**Comment by mjudeikis** [comment]
New image needed to be published under latest tag after https://github.com/openshift/openshift-azure/commit/bf3371a8a1592730604a7decce00503ebba88e8e

**Comment by mjudeikis** [comment]
v4.0-154-gbf3371a8a-clean nop :/

**Comment by mjudeikis** [comment]
@jim-minter your account has no email added to it, hence `nil` exception? 
![image](https://user-images.githubusercontent.com/3225744/56039169-923da080-5d2b-11e9-8996-6302dd36d1bf.png)


Where username is populated by email. Is this for sure right?
https://github.com/openshift/openshift-azure/pull/1493/files

**Comment by mjudeikis** [comment]
Despite the fact I added email to the profile dump is not showing it:
```
(*graphrbac.User)(0xc000151170)({                                                                                                                                                                                                                                                                                                                                                                                                       
 Response: (autorest.Response) {                                                                                                                                                                                                                                                                                                                                                                                                        
  Response: (*http.Response)(<nil>)                                                                                                                                                                                                                                                                                                                                                                                                     
 },                                                                                                                                                                                                                                                                                                                                                                                                                                     
 ImmutableID: (*string)(<nil>),                                                                                                                                                                                                                                                                                                                                                                                                         
 UsageLocation: (*string)(<nil>),                                                                                                                                                                                                                                                                                                                                                                                                       
 GivenName: (*string)(<nil>),
 Surname: (*string)(<nil>),
 UserType: (graphrbac.UserType) (len=6) "Member",
 AccountEnabled: (*bool)(0xc000725130)(false),
 DisplayName: (*string)(0xc000889220)((len=18) "Test User Disabled"),
 UserPrincipalName: (*string)(0xc000889260)((len=47) "testuserdisabled@rhcuppettgmail.onmicrosoft.com"),
 MailNickname: (*string)(0xc0008891a0)((len=16) "testuserdisabled"),
 Mail: (*string)(<nil>),
 SignInNames: (*[]graphrbac.SignInName)(0xc000734c00)({
 }),
 AdditionalProperties: (map[string]interface {}) (len=12) {
  (string) (len=14) "proxyAddresses": ([]interface {}) {
  },
  (string) (len=34) "thumbnailPhoto@odata.mediaEditLink": (string) (len=101) "directoryObjects/f1b3a6f7-0870-4125-bfcc-363084848e45/Microsoft.DirectoryServices.User/thumbnailPhoto",
  (string) (len=10) "otherMails": ([]interface {}) {
  },
  (string) (len=13) "assignedPlans": ([]interface {}) {
  },
  (string) (len=16) "assignedLicenses": ([]interface {}) {
  },
  (string) (len=15) "passwordProfile": (map[string]interface {}) (len=3) {
   (string) (len=8) "password": (interface {}) <nil>,
   (string) (len=28) "forceChangePasswordNextLogin": (bool) true,
   (string) (len=27) "enforceChangePasswordPolicy": (bool) false
  },
  (string) (len=10) "odata.type": (string) (len=32) "Microsoft.DirectoryServices.User",
  (string) (len=18) "provisioningErrors": ([]interface {}) {
  },
  (string) (len=16) "provisionedPlans": ([]interface {}) {
  },
  (string) (len=30) "refreshTokensValidFromDateTime": (string) (len=20) "2019-03-06T19:42:43Z",
  (string) (len=14) "userIdentities": ([]interface {}) {
  },
  (string) (len=15) "createdDateTime": (string) (len=20) "2019-03-06T19:42:44Z"
 },
 ObjectID: (*string)(0xc000889150)((len=36) "f1b3a6f7-0870-4125-bfcc-363084848e45"),
 DeletionTimestamp: (*date.Time)(<nil>),
 ObjectType: (graphrbac.ObjectType) (len=4) "User"
})

```

**Comment by mjudeikis** [comment]
We need test for this :/

**Comment by jim-minter** [comment]
thanks for the catch - we do.

perhaps mail is nil because the account is disabled.

**Comment by mjudeikis** [comment]
Did same change for your account - either sync lag or something is wrong...
