### ISSUE TITLE
timeout upgrading image in upgrade-v3.2 test

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1637]
We caught a timeout error during an upgrade-v3.2 test

```
panic: test timed out after 50m0s

goroutine 146 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive, 50 minutes]:
testing.(*T).Run(0xc000484300, 0x180b67d, 0x7, 0x18c0fb0, 0x481eb6)
	/usr/local/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc000484200)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc000484200, 0xc00059fe08)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc0002a1c00, 0x29b8890, 0x1, 0x1, 0x40d93f)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc00003ad80, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165FAIL	github.com/openshift/openshift-azure/test/e2e	3001.174s
signal: terminated
```

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1635/pull-ci-azure-master-upgrade-v3.2/198/build-log.txt

/kind test-flake

**Comment by ehashman** [comment]
upgrade-3.2 is long deprecated and I don't see any flakes from this for at least a month, so I'm assuming this is no longer applicable.

/close
