### ISSUE TITLE
createorupdate panic

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#168]
```
+ go run cmd/createorupdate/createorupdate.go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x58c107]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc4203b3da8)
	/usr/lib/golang/src/encoding/json/encode.go:290 +0x13e
panic(0xdf2920, 0x1591c80)
	/usr/lib/golang/src/runtime/panic.go:502 +0x229
encoding/json.(*encodeState).marshal.func1(0xc4203b3220)
	/usr/lib/golang/src/encoding/json/encode.go:290 +0x13e
panic(0xdf2920, 0x1591c80)
	/usr/lib/golang/src/runtime/panic.go:502 +0x229
crypto/rsa.(*PrivateKey).Precompute(0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:450 +0x37
crypto/x509.MarshalPKCS1PrivateKey(0x0, 0xc4201049a0, 0x0, 0xfd9ce0)
	/usr/lib/golang/src/crypto/x509/pkcs1.go:93 +0x40
github.com/openshift/openshift-azure/pkg/tls.PrivateKeyAsBytes(0x0, 0xc4202ec940, 0x96, 0xe288c0, 0x0, 0xc4202ec940)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/tls/marshal.go:28 +0x49
github.com/openshift/openshift-azure/pkg/config.CertKeyPair.MarshalJSON(0x0, 0x0, 0x410343, 0xdfbf20, 0xe2fba0, 0xe2fb01, 0x7f4d268791a0)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/config/marshal.go:179 +0x433
encoding/json.marshalerEncoder(0xc42011ad10, 0xe2fba0, 0xc420032a58, 0x99, 0x100)
	/usr/lib/golang/src/encoding/json/encode.go:445 +0x9c
encoding/json.(*structEncoder).encode(0xc420523c80, 0xc42011ad10, 0xec6260, 0xc420032968, 0x99, 0xec0100)
	/usr/lib/golang/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc42011ad10, 0xec6260, 0xc420032968, 0x99, 0xc420030100)
	/usr/lib/golang/src/encoding/json/encode.go:653 +0x64
encoding/json.(*encodeState).reflectValue(0xc42011ad10, 0xec6260, 0xc420032968, 0x99, 0xc420030100)
	/usr/lib/golang/src/encoding/json/encode.go:325 +0x82
encoding/json.interfaceEncoder(0xc42011ad10, 0xdd87a0, 0xc4202ed4c0, 0x94, 0xc4202e0100)
	/usr/lib/golang/src/encoding/json/encode.go:611 +0xdb
encoding/json.(*mapEncoder).encode(0xc42000e580, 0xc42011ad10, 0xdeb960, 0xc420522030, 0x15, 0xde0100)
	/usr/lib/golang/src/encoding/json/encode.go:684 +0x45f
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc42011ad10, 0xdeb960, 0xc420522030, 0x15, 0xc420520100)
	/usr/lib/golang/src/encoding/json/encode.go:700 +0x64
encoding/json.(*encodeState).reflectValue(0xc42011ad10, 0xdeb960, 0xc420522030, 0x15, 0x100)
	/usr/lib/golang/src/encoding/json/encode.go:325 +0x82
encoding/json.(*encodeState).marshal(0xc42011ad10, 0xdeb960, 0xc420522030, 0xc4203b0100, 0x0, 0x0)
	/usr/lib/golang/src/encoding/json/encode.go:298 +0xa5
encoding/json.Marshal(0xdeb960, 0xc420522030, 0x99, 0x31, 0xc4201dcf38, 0xc420032d38, 0x98)
	/usr/lib/golang/src/encoding/json/encode.go:161 +0x5f
github.com/openshift/openshift-azure/pkg/config.Config.MarshalJSON(0x1, 0xef189c, 0xb, 0xeee9e2, 0x6, 0xc42033cca0, 0xa, 0xeee95e, 0x6, 0xc4200380b4, ...)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/config/marshal.go:58 +0x9e1
encoding/json.marshalerEncoder(0xc42011a630, 0xdf5c80, 0xc4202f0480, 0x16, 0xc4202f0100)
	/usr/lib/golang/src/encoding/json/encode.go:445 +0x9c
encoding/json.(*encodeState).reflectValue(0xc42011a630, 0xdf5c80, 0xc4202f0480, 0x16, 0x100)
	/usr/lib/golang/src/encoding/json/encode.go:325 +0x82
encoding/json.(*encodeState).marshal(0xc42011a630, 0xdf5c80, 0xc4202f0480, 0x100, 0x0, 0x0)
	/usr/lib/golang/src/encoding/json/encode.go:298 +0xa5
encoding/json.Marshal(0xdf5c80, 0xc4202f0480, 0x0, 0x0, 0xc4200350a8, 0x1, 0x1)
	/usr/lib/golang/src/encoding/json/encode.go:161 +0x5f
github.com/openshift/openshift-azure/vendor/github.com/ghodss/yaml.Marshal(0xdf5c80, 0xc4202f0480, 0x0, 0x0, 0x0, 0x0, 0xfb28a0)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/vendor/github.com/ghodss/yaml/yaml.go:16 +0x39
github.com/openshift/openshift-azure/pkg/plugin.(*Plugin).GenerateConfig(0x15c0088, 0xc420342c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42033bf08)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/pkg/plugin/plugin.go:51 +0xd5
main.createOrUpdate(0xc420342840, 0x27f, 0x47f, 0xd6ce40)
	/home/kargakis/go/src/github.com/openshift/openshift-azure/cmd/createorupdate/createorupdate.go:66 +0x161
main.main()
	/home/kargakis/go/src/github.com/openshift/openshift-azure/cmd/createorupdate/createorupdate.go:173 +0xf5
exit status 2
```
@openshift/sig-azure

**Comment by kargakis** [comment]
false alarm, sorry for the noise
