### ISSUE TITLE
logbridge CrashLoopBackOff

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#581]
```
[root@master-000001 tmp]# oc get pods
NAME                        READY     STATUS             RESTARTS   AGE
api-master-000000           1/1       Running            0          1d
api-master-000001           1/1       Running            219        4m
api-master-000002           1/1       Running            5          1d
controllers-master-000000   1/1       Running            0          1d
controllers-master-000001   1/1       Running            3          4m
controllers-master-000002   1/1       Running            3          1d
etcd-master-000000          1/1       Running            0          1d
etcd-master-000001          1/1       Running            336        4m
etcd-master-000002          1/1       Running            1          1d
logbridge-compute-000000    0/1       CrashLoopBackOff   392        1d
logbridge-infra-000000      1/1       Running            1          1d
logbridge-infra-000001      1/1       Running            0          1d
logbridge-master-000000     1/1       Running            0          1d
logbridge-master-000001     1/1       Running            3          4m
logbridge-master-000002     0/1       CrashLoopBackOff   463        1d
sync-master-000000          1/1       Running            0          1d
[root@master-000001 tmp]# oc logs -f logbridge-compute-000000
panic: failed to seek to cursor "": 22

goroutine 1 [running]:
main.main()
        /data/home/jminter/go/src/github.com/openshift/openshift-azure/cmd/logbridge/main.go:194 +0x44
```

**Comment by mjudeikis** [comment]
good node:
```
[root@master-000001 tmp]# cat /var/lib/logbridge/cursor
s=1bb8dfb426fb4938b17c5f996273b44a;i=e00e0;b=7bad86be50d647fa9f4f53b83c392fef;m=26955e33d0;t=577de27c72d74;x=b543b160071b151b
```
broken:
```
[root@master-000002 ~]# cat /var/lib/logbridge/cursor
```

**Comment by mjudeikis** [comment]
cc: @jim-minter

**Comment by mjudeikis** [comment]
+ we might want to rebuild current image:
```
panic: failed to seek to cursor "": 22
goroutine 1 [running]:
main.main()
        /data/home/jminter/go/src/github.com/openshift/openshift-azure/cmd/logbridge/main.go:194 +0x44
```

**Comment by kargakis** [comment]
Ah we don't do any kind of build/promotion for logbridge.

**Comment by jim-minter** [comment]
I'm at a loss to explain the panic on main.go:194.  I fear that the built image does not correspond with the checked in code :-(

I also don't have an explanation for how the state/cursor file came to exist but was empty.

**Comment by jim-minter** [comment]
#587 protects against this and adds some logging - leaving issue open to try to discover root cause later
