### ISSUE TITLE
should deploy a template with persistent storage timeout

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#814]
```
• Failure [296.533 seconds]
Openshift on Azure end user e2e tests [EndUser]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:29
  should deploy a template with persistent storage and test failure modes [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:153

  Expected error:
      <*errors.errorString | 0xc0000838b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:238
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/798/pull-ci-openshift-openshift-azure-master-e2e-azure/1087/build-log.txt
Pods in the namespace:
<details>

```
metadata:
  annotations:
    openshift.io/build.name: django-psql-persistent-1
    openshift.io/scc: privileged
  creationTimestamp: 2018-11-30T09:55:09Z
  labels:
    openshift.io/build.name: django-psql-persistent-1
  name: django-psql-persistent-1-build
  namespace: e2e-test-4rt82
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: django-psql-persistent-1
    uid: 0590cdfd-f486-11e8-8b10-000d3a149b33
  resourceVersion: "5883"
  selfLink: /api/v1/namespaces/e2e-test-4rt82/pods/django-psql-persistent-1-build
  uid: 05a6a9b5-f486-11e8-8b10-000d3a149b33
spec:
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"django-psql-persistent-1","namespace":"e2e-test-4rt82","selfLink":"/apis/build.openshift.io/v1/namespaces/e2e-test-4rt82/builds/django-psql-persistent-1","uid":"0590cdfd-f486-11e8-8b10-000d3a149b33","resourceVersion":"5563","creationTimestamp":"2018-11-30T09:55:09Z","labels":{"app":"django-psql-persistent","buildconfig":"django-psql-persistent","openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.start-policy":"Serial","template":"django-psql-persistent","template.openshift.io/template-instance-owner":"053d8152-f486-11e8-8daa-000d3a149f50"},"annotations":{"openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"django-psql-persistent","uid":"055defd1-f486-11e8-8b10-000d3a149b33","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/sclorg/django-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e"},"pullSecret":{"name":"builder-dockercfg-7p2qz"},"env":[{"name":"PIP_INDEX_URL"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest"},"pushSecret":{"name":"builder-dockercfg-7p2qz"}},"resources":{},"postCommit":{"script":"./manage.py test"},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"python:3.6"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest","config":{"kind":"BuildConfig","namespace":"e2e-test-4rt82","name":"django-psql-persistent"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/sclorg/django-ex.git
    - name: SOURCE_URI
      value: https://github.com/sclorg/django-ex.git
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    - name: PULL_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/pull
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/crio/crio.sock
      name: crio-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-7p2qz-push
      readOnly: true
    - mountPath: /var/run/secrets/openshift.io/pull
      name: builder-dockercfg-7p2qz-pull
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-9wckf
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: builder-dockercfg-7p2qz
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"django-psql-persistent-1","namespace":"e2e-test-4rt82","selfLink":"/apis/build.openshift.io/v1/namespaces/e2e-test-4rt82/builds/django-psql-persistent-1","uid":"0590cdfd-f486-11e8-8b10-000d3a149b33","resourceVersion":"5563","creationTimestamp":"2018-11-30T09:55:09Z","labels":{"app":"django-psql-persistent","buildconfig":"django-psql-persistent","openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.start-policy":"Serial","template":"django-psql-persistent","template.openshift.io/template-instance-owner":"053d8152-f486-11e8-8daa-000d3a149f50"},"annotations":{"openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"django-psql-persistent","uid":"055defd1-f486-11e8-8b10-000d3a149b33","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/sclorg/django-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e"},"pullSecret":{"name":"builder-dockercfg-7p2qz"},"env":[{"name":"PIP_INDEX_URL"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest"},"pushSecret":{"name":"builder-dockercfg-7p2qz"}},"resources":{},"postCommit":{"script":"./manage.py test"},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"python:3.6"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest","config":{"kind":"BuildConfig","namespace":"e2e-test-4rt82","name":"django-psql-persistent"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/sclorg/django-ex.git
    - name: SOURCE_URI
      value: https://github.com/sclorg/django-ex.git
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-9wckf
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"django-psql-persistent-1","namespace":"e2e-test-4rt82","selfLink":"/apis/build.openshift.io/v1/namespaces/e2e-test-4rt82/builds/django-psql-persistent-1","uid":"0590cdfd-f486-11e8-8b10-000d3a149b33","resourceVersion":"5563","creationTimestamp":"2018-11-30T09:55:09Z","labels":{"app":"django-psql-persistent","buildconfig":"django-psql-persistent","openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.start-policy":"Serial","template":"django-psql-persistent","template.openshift.io/template-instance-owner":"053d8152-f486-11e8-8daa-000d3a149f50"},"annotations":{"openshift.io/build-config.name":"django-psql-persistent","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"django-psql-persistent","uid":"055defd1-f486-11e8-8b10-000d3a149b33","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/sclorg/django-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e"},"pullSecret":{"name":"builder-dockercfg-7p2qz"},"env":[{"name":"PIP_INDEX_URL"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest"},"pushSecret":{"name":"builder-dockercfg-7p2qz"}},"resources":{},"postCommit":{"script":"./manage.py test"},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"python:3.6"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest","config":{"kind":"BuildConfig","namespace":"e2e-test-4rt82","name":"django-psql-persistent"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/sclorg/django-ex.git
    - name: SOURCE_URI
      value: https://github.com/sclorg/django-ex.git
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-9wckf
      readOnly: true
  nodeName: compute-000000
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: buildworkdir
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket
  - hostPath:
      path: /var/run/crio/crio.sock
      type: ""
    name: crio-socket
  - name: builder-dockercfg-7p2qz-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-7p2qz
  - name: builder-dockercfg-7p2qz-pull
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-7p2qz
  - name: builder-token-9wckf
    secret:
      defaultMode: 420
      secretName: builder-token-9wckf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:55:15Z
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:17Z
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:55:09Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://72500357d6adea6a367ee68a19df2f1b38160e0ce454b0400657d6012997510c
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imageID: docker-pullable://registry.access.redhat.com/openshift3/ose-docker-builder@sha256:c6d8a052a3a4c892acb1ac033531535559040d6aa142260ef5ff029effe5ada0
    lastState: {}
    name: sti-build
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://72500357d6adea6a367ee68a19df2f1b38160e0ce454b0400657d6012997510c
        exitCode: 0
        finishedAt: 2018-11-30T09:56:16Z
        reason: Completed
        startedAt: 2018-11-30T09:55:16Z
  hostIP: 10.0.0.9
  initContainerStatuses:
  - containerID: docker://cf141f343cbfaa2a28beb99866a01110123b0550ad09fb223f8b1085cfd12634
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imageID: docker-pullable://registry.access.redhat.com/openshift3/ose-docker-builder@sha256:c6d8a052a3a4c892acb1ac033531535559040d6aa142260ef5ff029effe5ada0
    lastState: {}
    name: git-clone
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://cf141f343cbfaa2a28beb99866a01110123b0550ad09fb223f8b1085cfd12634
        exitCode: 0
        finishedAt: 2018-11-30T09:55:13Z
        reason: Completed
        startedAt: 2018-11-30T09:55:12Z
  - containerID: docker://a998b27aa549233b2868a2ee76dc782df06df450a09c14494a007c2237d2476c
    image: registry.access.redhat.com/openshift3/ose-docker-builder:v3.11.43
    imageID: docker-pullable://registry.access.redhat.com/openshift3/ose-docker-builder@sha256:c6d8a052a3a4c892acb1ac033531535559040d6aa142260ef5ff029effe5ada0
    lastState: {}
    name: manage-dockerfile
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://a998b27aa549233b2868a2ee76dc782df06df450a09c14494a007c2237d2476c
        exitCode: 0
        finishedAt: 2018-11-30T09:55:15Z
        reason: Completed
        startedAt: 2018-11-30T09:55:15Z
  phase: Succeeded
  podIP: 10.129.2.7
  qosClass: BestEffort
  startTime: 2018-11-30T09:55:09Z

metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: django-psql-persistent
    openshift.io/deployment.name: django-psql-persistent-1
    openshift.io/scc: restricted
  creationTimestamp: 2018-11-30T09:56:19Z
  generateName: django-psql-persistent-1-
  labels:
    deployment: django-psql-persistent-1
    deploymentconfig: django-psql-persistent
    name: django-psql-persistent
  name: django-psql-persistent-1-lmsbh
  namespace: e2e-test-4rt82
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: django-psql-persistent-1
    uid: 2d8b6384-f486-11e8-8b10-000d3a149b33
  resourceVersion: "6614"
  selfLink: /api/v1/namespaces/e2e-test-4rt82/pods/django-psql-persistent-1-lmsbh
  uid: 2f851d41-f486-11e8-8b10-000d3a149b33
spec:
  containers:
  - env:
    - name: DATABASE_SERVICE_NAME
      value: postgresql
    - name: DATABASE_ENGINE
      value: postgresql
    - name: DATABASE_NAME
      value: default
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: django-psql-persistent
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: django-psql-persistent
    - name: APP_CONFIG
    - name: DJANGO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: django-secret-key
          name: django-psql-persistent
    image: docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent@sha256:0d4bd6f795ad8ae01934d89e27a324c44a2b6fdfcebab37ede200599affd505d
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: django-psql-persistent
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000290000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dhs8h
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-4gfgv
  nodeName: compute-000000
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000290000
    seLinuxOptions:
      level: s0:c17,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-dhs8h
    secret:
      defaultMode: 420
      secretName: default-token-dhs8h
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:19Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:58Z
    message: 'containers with unready status: [django-psql-persistent]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'containers with unready status: [django-psql-persistent]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:19Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://26bee4d9926f0e691398a28217a84c5bec3c863000e29b155f72495fd597414b
    image: docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent:latest
    imageID: docker-pullable://docker-registry.default.svc:5000/e2e-test-4rt82/django-psql-persistent@sha256:0d4bd6f795ad8ae01934d89e27a324c44a2b6fdfcebab37ede200599affd505d
    lastState:
      terminated:
        containerID: docker://26bee4d9926f0e691398a28217a84c5bec3c863000e29b155f72495fd597414b
        exitCode: 1
        finishedAt: 2018-11-30T09:59:22Z
        reason: Error
        startedAt: 2018-11-30T09:59:18Z
    name: django-psql-persistent
    ready: false
    restartCount: 5
    state:
      waiting:
        message: Back-off 1m20s restarting failed container=django-psql-persistent
          pod=django-psql-persistent-1-lmsbh_e2e-test-4rt82(2f851d41-f486-11e8-8b10-000d3a149b33)
        reason: CrashLoopBackOff
  hostIP: 10.0.0.9
  phase: Running
  podIP: 10.129.2.11
  qosClass: Burstable
  startTime: 2018-11-30T09:56:19Z

metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: postgresql
    openshift.io/deployment.name: postgresql-1
    openshift.io/scc: restricted
  creationTimestamp: 2018-11-30T09:56:33Z
  generateName: postgresql-1-
  labels:
    deployment: postgresql-1
    deploymentconfig: postgresql
    name: postgresql
  name: postgresql-1-tzd77
  namespace: e2e-test-4rt82
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: postgresql-1
    uid: 0630f202-f486-11e8-8b10-000d3a149b33
  resourceVersion: "6602"
  selfLink: /api/v1/namespaces/e2e-test-4rt82/pods/postgresql-1-tzd77
  uid: 37b8a3a7-f486-11e8-8b10-000d3a149b33
spec:
  containers:
  - env:
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: django-psql-persistent
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: django-psql-persistent
    - name: POSTGRESQL_DATABASE
      value: default
    image: docker-registry.default.svc:5000/openshift/postgresql@sha256:52784d5e55d82076ac5f809ed6d298af6bac2003e2cfe1f0099123deefc45da1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/libexec/check-container
        - --live
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: postgresql
    ports:
    - containerPort: 5432
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /usr/libexec/check-container
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000290000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/pgsql/data
      name: postgresql-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dhs8h
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-4gfgv
  nodeName: compute-000000
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000290000
    seLinuxOptions:
      level: s0:c17,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: postgresql
  - name: default-token-dhs8h
    secret:
      defaultMode: 420
      secretName: default-token-dhs8h
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:33Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:59:22Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-11-30T09:56:33Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2dee10305e2b5a76c45bda104499e564ae963d781e049620712b030ec9e40517
    image: sha256:84515da73c80bf3d05a750bb794493b655d15843fbc46b1e767f1f5d4c639b1d
    imageID: docker-pullable://docker-registry.default.svc:5000/openshift/postgresql@sha256:52784d5e55d82076ac5f809ed6d298af6bac2003e2cfe1f0099123deefc45da1
    lastState: {}
    name: postgresql
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-11-30T09:59:13Z
  hostIP: 10.0.0.9
  phase: Running
  podIP: 10.129.2.12
  qosClass: Burstable
  startTime: 2018-11-30T09:56:33Z
```
</details>
/kind test-flake

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/830/pull-ci-openshift-openshift-azure-master-e2e-azure/1153

**Comment by kargakis** [comment]
Had a duplicate issue of this with some testdata in https://github.com/openshift/openshift-azure/issues/863

**Comment by kargakis** [comment]
Btw in one of the failure modes of this test, we should avoid panicking at least to allow the test to get artifacts. Seems the panic comes from `go test` timing out so we need to figure out why the test was stuck in the first place.
```
STEP: instantiating the template and getting the route (2018-12-19 13:19:13.948512208 +0000 UTC m=+630.515258524)
panic: test timed out after 20m0s

goroutine 767 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```

**Comment by kargakis** [comment]
Another failure mode:
```
Openshift on Azure end user e2e tests [EndUser][Fake]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:29
  should deploy a template with persistent storage and test failure modes [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:149

  Expected error:
      <*errors.errorString | 0xc000361b20>: {
          s: "templateinstance e2e-test-agmmb failed",
      }
      templateinstance e2e-test-agmmb failed
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:187
```
Looks like the build failed to pull from the registry
```
pulling image error : error pulling image configuration: unknown blob
          error: build error: unable to get docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/921/pull-ci-openshift-openshift-azure-master-e2e-azure/1560

**Comment by kargakis** [comment]
> Btw in one of the failure modes of this test, we should avoid panicking at least to allow the test to get artifacts. Seems the panic comes from `go test` timing out so we need to figure out why the test was stuck in the first place.

This is fixed in https://github.com/openshift/openshift-azure/pull/946

**Comment by kargakis** [comment]
To reduce the flakiness of this test I would suggest deploying a standalone StatefulSet (no Builds, no Templates) that pulls postgres from our quay registry and instead of going through a route to increment the counter, we exec inside the database pod and use its cli tool to mutate its state.

**Comment by thekad** [comment]
The goal was to have a couple of tests where a template was instantiated, this being one of them. We could change the test and focus entirely on the persistent storage piece of it, since we already have another test for template instantiation though.

**Comment by kargakis** [comment]
I am not sure about the template instantiation part - it's not unique to
OSA and it should already be covered by the origin conformance suite.

**Comment by jim-minter** [comment]
I'm reluctant to remove/break up this test right now - a) it represents a common use case, and b) it is a visible inline test whereas the conformance results are not at all visible yet.
If there are particular flakes which we're seeing, we should work out how to deal with them on a case by case basis.

**Comment by jim-minter** [comment]
If there have been recent flakes on this test, append them here and investigate them, otherwise close the issue.

**Comment by thekad** [comment]
There hadn't been any flakes with this particular test since last month, until this morning: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure/97/ *but* in this case the failure presented on the second round of GETs after the database is supposed to come back e.g. no builds or image pulls happened.

**Comment by mjudeikis** [comment]
reopen if needed

**Comment by jim-minter** [comment]
old flake - since then have fixed a storage issue + increased timeout from 10 to 20 minutes
open a new issue if further createStatefulApp errors seen.
